services:
  api1:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1@sha256:2501d47dd8426dc08b37c0ae83d8a218fedf1cbf3f6949f032f13ce1757d395c
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  api2:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1@sha256:2501d47dd8426dc08b37c0ae83d8a218fedf1cbf3f6949f032f13ce1757d395c
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  lb:
    platform: linux/amd64
    image: nginx:alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"

networks:
  rinha:
    driver: bridge
