services:
  api1:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1@sha256:73ad52bfb227d5fa5810f633d9c2fcfd0059446f839f377efb2bad92e1e393b1
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  api2:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1@sha256:73ad52bfb227d5fa5810f633d9c2fcfd0059446f839f377efb2bad92e1e393b1
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  lb:
    platform: linux/amd64
    image: nginx:alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"

networks:
  rinha:
    driver: bridge
