services:
  api1:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1:latest
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  api2:
    platform: linux/amd64
    image: rmoraes4/rinha-2026-python1:latest
    environment:
      - PORT=8000
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160M"

  lb:
    platform: linux/amd64
    image: nginx:alpine
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30M"

networks:
  rinha:
    driver: bridge
